language: rust
dist: xenial
rust:
  - stable
  - beta
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y gcc-arm-none-eabi gcc clang-3.9 libclang-3.9-dev llvm-3.9-dev git
install:
  - rustup target add thumbv8m.main-none-eabi
jobs:
  include:
    - script:
        - git clone https://github.com/NordicPlayground/nrfxlib ~/nrfxlib
        - NRFXLIB_PATH=~/nrfxlib NEWLIB_PATH=/usr/include/newlib cargo build
    - script:
        - git clone https://github.com/NordicPlayground/nrfxlib ~/nrfxlib
        - git checkout tags/v1.0.0 -C ~/nrfxlib
        - NRFXLIB_PATH=~/nrfxlib NEWLIB_PATH=/usr/include/newlib cargo build
