[package]
name = "nrfxlib-sys"
version = "0.1.7"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
edition = "2018"
description = "Rust bindings to the Nordic nRF9160 Socket Library."
readme = "README.md"
license-file = "LICENCE.md"
repository = "https://github.com/thejpster/nrfxlib-sys"

[dependencies]

[build-dependencies]
cargo-5730 = "0.2"

[workaround-build-dependencies]
bindgen = "0.49"
