[package]
name = "nrfxlib-sys"
version = "0.1.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
edition = "2018"
description = "Rust bindings to the Nordic nRF9160 Socket Library."
readme = "README.md"
license-file = "LICENCE.md"

[dependencies]

[build-dependencies]
bindgen = "0.49"
